/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Mp3Player;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Melissa
 */
public final class MusicGui extends javax.swing.JFrame {

    /**
     * Creates new form MusicGui
     */
    private ArrayList<String> tones = new ArrayList();
    MP3Player Player = new MP3Player();
    public MusicGui() {
        initComponents();
        AddTones();
        MusicList.setListData(ConvertTones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MusicList = new javax.swing.JList();
        MusicLabel = new javax.swing.JLabel();
        UploadButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        PauseButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();

        setTitle("Alarm Tones");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        MusicList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MusicList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "good-morning.mp3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        MusicList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(MusicList);

        MusicLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MusicLabel.setForeground(new java.awt.Color(255, 255, 255));
        MusicLabel.setText("List of Tones:");
        MusicLabel.setToolTipText("");

        UploadButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        UploadButton.setText("+");
        UploadButton.setToolTipText("");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        DeleteButton.setText("-");
        DeleteButton.setToolTipText("");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        PlayButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartalarm/images/1476496988_Go.png"))); // NOI18N
        PlayButton.setToolTipText("");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        PauseButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartalarm/images/1476497054_icon-ios7-pause.png"))); // NOI18N
        PauseButton.setToolTipText("");
        PauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseButtonActionPerformed(evt);
            }
        });

        StopButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        StopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartalarm/images/1476497110_player_stop.png"))); // NOI18N
        StopButton.setToolTipText("");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(MusicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UploadButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PlayButton)
                        .addGap(18, 18, 18)
                        .addComponent(PauseButton)
                        .addGap(34, 34, 34)
                        .addComponent(StopButton)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MusicLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UploadButton)
                            .addComponent(DeleteButton))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PauseButton)
                            .addComponent(PlayButton)
                            .addComponent(StopButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
       if(!MusicList.isSelectionEmpty()){
           String musicpath = MusicList.getSelectedValue().toString();
           if(musicpath != null || !musicpath.isEmpty()){
                Player.Play(musicpath);
            }
       }
       else{
           JOptionPane.showMessageDialog(this,"Please select a music file","Error",JOptionPane.ERROR_MESSAGE);
       }
        
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void PauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseButtonActionPerformed

        Player.Pause();
    }//GEN-LAST:event_PauseButtonActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        Player.Stop();
    }//GEN-LAST:event_StopButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int [] deleted = MusicList.getSelectedIndices();
        for(int i =0; i< deleted.length; i++){
            tones.remove(deleted[i]);
        }
        MusicList.setListData(ConvertTones());
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        JFileChooser chooser= new JFileChooser();
        //only mp3 files will make the import button visible
        FileNameExtensionFilter filter = new FileNameExtensionFilter("mp3 file","mp3");
        chooser.setFileFilter(filter);
        int choice = chooser.showOpenDialog(null);
        
        if (choice != JFileChooser.APPROVE_OPTION) return;

        File chosenFile = chooser.getSelectedFile();
        String filename = chosenFile.getName();
        String extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
        if(!extension.equals("mp3")){
            JOptionPane.showMessageDialog(jPanel1,"Wrong File Format!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            tones.add(chosenFile.getName());
        MusicList.setListData(ConvertTones());
        }
        
        
    }//GEN-LAST:event_UploadButtonActionPerformed
    public void AddTones(){
        tones.add("nothingatall.mp3");
    }
    private String [] ConvertTones(){
        String [] tonescontainer = new String [tones.size()];
        for(int t =0; t<tones.size(); t++){
            tonescontainer[t]= tones.get(t);
        }
        return tonescontainer;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel MusicLabel;
    private javax.swing.JList MusicList;
    private javax.swing.JButton PauseButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton StopButton;
    private javax.swing.JButton UploadButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private static class ArrayListImpl extends ArrayList {

        public ArrayListImpl() {
        }
    }
}
